### ISSUE TITLE
想问一下，新闻中出现新闻客户端版本太低了，升级之后就能看到更多的新闻方式了，是什么原因呢

### ISSUE THREAD

**Issue by 1414648814** [Ashen-Zhao/zhishiNews#1]

**Comment by ashen-zhao** [comment]
你是指哪个新闻客户端？  问题太模糊，升级是更新版本吗？如果是，版本更新了可能加了低版本没有的功能，而且低版本时，已经加入可以判断这种情况的处理。

**Comment by 1414648814** [comment]
就是知事，点击新闻cell后，进入的内容显示新闻客户端版本太低了，升级之后就能看到更多的新闻方式了

**Comment by ashen-zhao** [comment]
哦，原来是上面显示升级后，不是你已经升级了，懂了；
那是因为新闻内容有多种，我只处理了部分类型，有些类型没处理的，你可以看下那个新闻是什么类型，然后过滤到就行了

**Comment by 1414648814** [comment]
过滤是什么意思呢？
能告诉我是那段代码吗？

**Comment by 1414648814** [comment]
还有个问题，就是你是如何进行获取到网站发送回json网址呢，由于我本人最近在弄音乐app，但是不知道获取音乐数据的网址，所以问问你

**Comment by ashen-zhao** [comment]
https://github.com/ashen-zhao/linjiaMusic 这个是音乐App， 置于你说的，不知道如何获取数据网址，这需要抓包类软件，利用charles这个软件，可以抓取某些应用的接口网址

**Comment by 1414648814** [comment]
感谢🙏
